#!/usr/bin/env python3
"""
Create (or update) myproj/_version.py based on git tags.
Outputs a simple __version__ string derived from `git describe`.
"""

import subprocess
import textwrap
from pathlib import Path

PACKAGE = "src"  # <--- change to your package/dir name
OUT = Path(PACKAGE) / "_version.py"


def git_describe():
    try:
        # Try a descriptive tag: v1.2.3-4-g<sha> or v1.2.3
        s = (
            subprocess.check_output(
                ["git", "describe", "--tags", "--long", "--always", "--dirty"],
                stderr=subprocess.DEVNULL,
            )
            .decode()
            .strip()
        )
        return s
    except Exception:
        return None


def normalize(describe):
    # Keep it simple: if there's a tag like v1.2.3, remove leading 'v'.
    # If it's like v1.2.3-4-gabc, convert to v1.2.3.dev4+gabc (optional).
    if not describe:
        return "0.0.0+unknown"
    if "-" not in describe:
        return describe.lstrip("v")
    # example: v1.2.3-4-gabc123 -> 1.2.3.dev4+gabc123
    parts = describe.split("-", 2)
    tag = parts[0].lstrip("v")
    commits = parts[1]
    g = parts[2] if len(parts) > 2 else ""
    g = g.lstrip("g")
    return f"{tag}.dev{commits}+{g}"


def write_version(ver):
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        textwrap.dedent(
            f"""\
        # This file is autogenerated by tools/generate_version.py
        __version__ = \"{ver}\"
        """
        )
    )
    print(f"Wrote {OUT} -> {ver}")


if __name__ == "__main__":
    desc = git_describe()
    version = normalize(desc)
    write_version(version)
